name: web_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.1
  flutter_inappwebview: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  share_plus: ^12.0.0
  flutter_tts: ^4.2.3
  google_fonts: ^6.3.1
  intl: ^0.20.2
  iconsax_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  web: ^0.5.1

flutter:
  uses-material-design: true
